package com.classy.class_2021a_ands_3;

import java.util.ArrayList;

public class CurrencyManager {

    public static MyCurrency[] CURRENCIES = new MyCurrency[]{
            new MyCurrency("Albania Lek", "ALL", "Lek"),
            new MyCurrency("Afghanistan Afghani", "AFN", "؋"),
            new MyCurrency("Argentina Peso", "ARS", "$"),
            new MyCurrency("Aruba Guilder", "AWG", "ƒ"),
            new MyCurrency("Australia Dollar", "AUD", "$"),
            new MyCurrency("Azerbaijan Manat", "AZN", "₼"),
            new MyCurrency("Bahamas Dollar", "BSD", "$"),
            new MyCurrency("Barbados Dollar", "BBD", "$"),
            new MyCurrency("Belarus Ruble", "BYN", "Br"),
            new MyCurrency("Belize Dollar", "BZD", "BZ$"),
            new MyCurrency("Bermuda Dollar", "BMD", "$"),
            new MyCurrency("Bolivia Bolíviano", "BOB", "$b"),
            new MyCurrency("Bosnia and Herzegovina Convertible Marka", "BAM", "KM"),
            new MyCurrency("Botswana Pula", "BWP", "P"),
            new MyCurrency("Bulgaria Lev", "BGN", "лв"),
            new MyCurrency("Brazil Real", "BRL", "R$"),
            new MyCurrency("Brunei Darussalam Dollar", "BND", "$"),
            new MyCurrency("Cambodia Riel", "KHR", "៛"),
            new MyCurrency("Canada Dollar", "CAD", "$"),
            new MyCurrency("Cayman Islands Dollar", "KYD", "$"),
            new MyCurrency("Chile Peso", "CLP", "$"),
            new MyCurrency("China Yuan Renminbi", "CNY", "¥"),
            new MyCurrency("Colombia Peso", "COP", "$"),
            new MyCurrency("Costa Rica Colon", "CRC", "₡"),
            new MyCurrency("Croatia Kuna", "HRK", "kn"),
            new MyCurrency("Cuba Peso", "CUP", "₱"),
            new MyCurrency("Czech Republic Koruna", "CZK", "Kč"),
            new MyCurrency("Denmark Krone", "DKK", "kr"),
            new MyCurrency("Dominican Republic Peso", "DOP", "RD$"),
            new MyCurrency("East Caribbean Dollar", "XCD", "$"),
            new MyCurrency("Egypt Pound", "EGP", "£"),
            new MyCurrency("El Salvador Colon", "SVC", "$"),
            new MyCurrency("Euro Member Countries", "EUR", "€"),
            new MyCurrency("Falkland Islands (Malvinas) Pound", "FKP", "£"),
            new MyCurrency("Fiji Dollar", "FJD", "$"),
            new MyCurrency("Ghana Cedi", "GHS", "¢"),
            new MyCurrency("Gibraltar Pound", "GIP", "£"),
            new MyCurrency("Guatemala Quetzal", "GTQ", "Q"),
            new MyCurrency("Guernsey Pound", "GGP", "£"),
            new MyCurrency("Guyana Dollar", "GYD", "$"),
            new MyCurrency("Honduras Lempira", "HNL", "L"),
            new MyCurrency("Hong Kong Dollar", "HKD", "$"),
            new MyCurrency("Hungary Forint", "HUF", "Ft"),
            new MyCurrency("Iceland Krona", "ISK", "kr"),
            new MyCurrency("India Rupee", "INR", "₹"),
            new MyCurrency("Indonesia Rupiah", "IDR", "Rp"),
            new MyCurrency("Iran Rial", "IRR", "﷼"),
            new MyCurrency("Isle of Man Pound", "IMP", "£"),
            new MyCurrency("Israel Shekel", "ILS", "₪"),
            new MyCurrency("Jamaica Dollar", "JMD", "J$"),
            new MyCurrency("Japan Yen", "JPY", "¥"),
            new MyCurrency("Jersey Pound", "JEP", "£"),
            new MyCurrency("Kazakhstan Tenge", "KZT", "лв"),
            new MyCurrency("Korea (North) Won", "KPW", "₩"),
            new MyCurrency("Korea (South) Won", "KRW", "₩"),
            new MyCurrency("Kyrgyzstan Som", "KGS", "лв"),
            new MyCurrency("Laos Kip", "LAK", "₭"),
            new MyCurrency("Lebanon Pound", "LBP", "£"),
            new MyCurrency("Liberia Dollar", "LRD", "$"),
            new MyCurrency("Macedonia Denar", "MKD", "ден"),
            new MyCurrency("Malaysia Ringgit", "MYR", "RM"),
            new MyCurrency("Mauritius Rupee", "MUR", "₨"),
            new MyCurrency("Mexico Peso", "MXN", "$"),
            new MyCurrency("Mongolia Tughrik", "MNT", "₮"),
            new MyCurrency("Mozambique Metical", "MZN", "MT"),
            new MyCurrency("Namibia Dollar", "NAD", "$"),
            new MyCurrency("Nepal Rupee", "NPR", "₨"),
            new MyCurrency("Netherlands Antilles Guilder", "ANG", "ƒ"),
            new MyCurrency("New Zealand Dollar", "NZD", "$"),
            new MyCurrency("Nicaragua Cordoba", "NIO", "C$"),
            new MyCurrency("Nigeria Naira", "NGN", "₦"),
            new MyCurrency("Norway Krone", "NOK", "kr"),
            new MyCurrency("Oman Rial", "OMR", "﷼"),
            new MyCurrency("Pakistan Rupee", "PKR", "₨"),
            new MyCurrency("Panama Balboa", "PAB", "B/."),
            new MyCurrency("Paraguay Guarani", "PYG", "Gs"),
            new MyCurrency("Peru Sol", "PEN", "S/."),
            new MyCurrency("Philippines Peso", "PHP", "₱"),
            new MyCurrency("Poland Zloty", "PLN", "zł"),
            new MyCurrency("Qatar Riyal", "QAR", "﷼"),
            new MyCurrency("Romania Leu", "RON", "lei"),
            new MyCurrency("Russia Ruble", "RUB", "₽"),
            new MyCurrency("Saint Helena Pound", "SHP", "£"),
            new MyCurrency("Saudi Arabia Riyal", "SAR", "﷼"),
            new MyCurrency("Serbia Dinar", "RSD", "Дин."),
            new MyCurrency("Seychelles Rupee", "SCR", "₨"),
            new MyCurrency("Singapore Dollar", "SGD", "$"),
            new MyCurrency("Solomon Islands Dollar", "SBD", "$"),
            new MyCurrency("Somalia Shilling", "SOS", "S"),
            new MyCurrency("South Africa Rand", "ZAR", "R"),
            new MyCurrency("Sri Lanka Rupee", "LKR", "₨"),
            new MyCurrency("Sweden Krona", "SEK", "kr"),
            new MyCurrency("Switzerland Franc", "CHF", "CHF"),
            new MyCurrency("Suriname Dollar", "SRD", "$"),
            new MyCurrency("Syria Pound", "SYP", "£"),
            new MyCurrency("Taiwan New Dollar", "TWD", "NT$"),
            new MyCurrency("Thailand Baht", "THB", "฿"),
            new MyCurrency("Trinidad and Tobago Dollar", "TTD", "TT$"),
            new MyCurrency("Turkey Lira", "TRY", "₺"),
            new MyCurrency("Tuvalu Dollar", "TVD", "$"),
            new MyCurrency("Ukraine Hryvnia", "UAH", "₴"),
            new MyCurrency("United Kingdom Pound", "GBP", "£"),
            new MyCurrency("United States Dollar", "USD", "$"),
            new MyCurrency("Uruguay Peso", "UYU", "$U"),
            new MyCurrency("Uzbekistan Som", "UZS", "лв"),
            new MyCurrency("Venezuela Bolívar", "VEF", "Bs"),
            new MyCurrency("Viet Nam Dong", "VND", "₫"),
            new MyCurrency("Yemen Rial", "YER", "﷼"),
            new MyCurrency("Zimbabwe Dollar", "ZWD", "Z$")
    };


    public static class MyCurrency {
        public String name;
        public String code;
        public String symbol;

        public MyCurrency(String name, String code, String symbol) {
            this.name = name;
            this.code = code;
            this.symbol = symbol;
        }
    }
}